# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [feature/002-CI-Configuration-2]
  pull_request:
    branches: [feature/002-CI-Configuration-2]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: mvn install
    - name: Test
      run: mvn test
    - name: JavaDoc
      run: mvn javadoc:javadoc
